/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienceIndexRouteImport } from './routes/experience.index'
import { Route as ExperienceSecopsRouteImport } from './routes/experience.secops'
import { Route as ExperienceSecopsIndexRouteImport } from './routes/experience.secops.index'
import { Route as ExperienceSecopsWhyRouteImport } from './routes/experience.secops.why'
import { Route as ExperienceSecopsTourRouteImport } from './routes/experience.secops.tour'
import { Route as ExperienceSecopsSuccessRouteImport } from './routes/experience.secops.success'
import { Route as ExperienceSecopsStoriesRouteImport } from './routes/experience.secops.stories'
import { Route as ExperienceSecopsBookRouteImport } from './routes/experience.secops.book'
import { Route as ExperienceSecopsAiRouteImport } from './routes/experience.secops.ai'
import { Route as ExperienceSecopsTourCapabilityRouteImport } from './routes/experience.secops.tour.$capability'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSecopsRoute = ExperienceSecopsRouteImport.update({
  id: '/experience/secops',
  path: '/experience/secops',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSecopsIndexRoute = ExperienceSecopsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperienceSecopsRoute,
} as any)
const ExperienceSecopsWhyRoute = ExperienceSecopsWhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => ExperienceSecopsRoute,
} as any)
const ExperienceSecopsTourRoute = ExperienceSecopsTourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => ExperienceSecopsRoute,
} as any)
const ExperienceSecopsSuccessRoute = ExperienceSecopsSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ExperienceSecopsRoute,
} as any)
const ExperienceSecopsStoriesRoute = ExperienceSecopsStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => ExperienceSecopsRoute,
} as any)
const ExperienceSecopsBookRoute = ExperienceSecopsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ExperienceSecopsRoute,
} as any)
const ExperienceSecopsAiRoute = ExperienceSecopsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => ExperienceSecopsRoute,
} as any)
const ExperienceSecopsTourCapabilityRoute =
  ExperienceSecopsTourCapabilityRouteImport.update({
    id: '/$capability',
    path: '/$capability',
    getParentRoute: () => ExperienceSecopsTourRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/experience/secops': typeof ExperienceSecopsRouteWithChildren
  '/experience/': typeof ExperienceIndexRoute
  '/experience/secops/ai': typeof ExperienceSecopsAiRoute
  '/experience/secops/book': typeof ExperienceSecopsBookRoute
  '/experience/secops/stories': typeof ExperienceSecopsStoriesRoute
  '/experience/secops/success': typeof ExperienceSecopsSuccessRoute
  '/experience/secops/tour': typeof ExperienceSecopsTourRouteWithChildren
  '/experience/secops/why': typeof ExperienceSecopsWhyRoute
  '/experience/secops/': typeof ExperienceSecopsIndexRoute
  '/experience/secops/tour/$capability': typeof ExperienceSecopsTourCapabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/experience': typeof ExperienceIndexRoute
  '/experience/secops/ai': typeof ExperienceSecopsAiRoute
  '/experience/secops/book': typeof ExperienceSecopsBookRoute
  '/experience/secops/stories': typeof ExperienceSecopsStoriesRoute
  '/experience/secops/success': typeof ExperienceSecopsSuccessRoute
  '/experience/secops/tour': typeof ExperienceSecopsTourRouteWithChildren
  '/experience/secops/why': typeof ExperienceSecopsWhyRoute
  '/experience/secops': typeof ExperienceSecopsIndexRoute
  '/experience/secops/tour/$capability': typeof ExperienceSecopsTourCapabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/experience/secops': typeof ExperienceSecopsRouteWithChildren
  '/experience/': typeof ExperienceIndexRoute
  '/experience/secops/ai': typeof ExperienceSecopsAiRoute
  '/experience/secops/book': typeof ExperienceSecopsBookRoute
  '/experience/secops/stories': typeof ExperienceSecopsStoriesRoute
  '/experience/secops/success': typeof ExperienceSecopsSuccessRoute
  '/experience/secops/tour': typeof ExperienceSecopsTourRouteWithChildren
  '/experience/secops/why': typeof ExperienceSecopsWhyRoute
  '/experience/secops/': typeof ExperienceSecopsIndexRoute
  '/experience/secops/tour/$capability': typeof ExperienceSecopsTourCapabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/experience/secops'
    | '/experience/'
    | '/experience/secops/ai'
    | '/experience/secops/book'
    | '/experience/secops/stories'
    | '/experience/secops/success'
    | '/experience/secops/tour'
    | '/experience/secops/why'
    | '/experience/secops/'
    | '/experience/secops/tour/$capability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/experience'
    | '/experience/secops/ai'
    | '/experience/secops/book'
    | '/experience/secops/stories'
    | '/experience/secops/success'
    | '/experience/secops/tour'
    | '/experience/secops/why'
    | '/experience/secops'
    | '/experience/secops/tour/$capability'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/experience/secops'
    | '/experience/'
    | '/experience/secops/ai'
    | '/experience/secops/book'
    | '/experience/secops/stories'
    | '/experience/secops/success'
    | '/experience/secops/tour'
    | '/experience/secops/why'
    | '/experience/secops/'
    | '/experience/secops/tour/$capability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ExperienceSecopsRoute: typeof ExperienceSecopsRouteWithChildren
  ExperienceIndexRoute: typeof ExperienceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/secops': {
      id: '/experience/secops'
      path: '/experience/secops'
      fullPath: '/experience/secops'
      preLoaderRoute: typeof ExperienceSecopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/secops/': {
      id: '/experience/secops/'
      path: '/'
      fullPath: '/experience/secops/'
      preLoaderRoute: typeof ExperienceSecopsIndexRouteImport
      parentRoute: typeof ExperienceSecopsRoute
    }
    '/experience/secops/why': {
      id: '/experience/secops/why'
      path: '/why'
      fullPath: '/experience/secops/why'
      preLoaderRoute: typeof ExperienceSecopsWhyRouteImport
      parentRoute: typeof ExperienceSecopsRoute
    }
    '/experience/secops/tour': {
      id: '/experience/secops/tour'
      path: '/tour'
      fullPath: '/experience/secops/tour'
      preLoaderRoute: typeof ExperienceSecopsTourRouteImport
      parentRoute: typeof ExperienceSecopsRoute
    }
    '/experience/secops/success': {
      id: '/experience/secops/success'
      path: '/success'
      fullPath: '/experience/secops/success'
      preLoaderRoute: typeof ExperienceSecopsSuccessRouteImport
      parentRoute: typeof ExperienceSecopsRoute
    }
    '/experience/secops/stories': {
      id: '/experience/secops/stories'
      path: '/stories'
      fullPath: '/experience/secops/stories'
      preLoaderRoute: typeof ExperienceSecopsStoriesRouteImport
      parentRoute: typeof ExperienceSecopsRoute
    }
    '/experience/secops/book': {
      id: '/experience/secops/book'
      path: '/book'
      fullPath: '/experience/secops/book'
      preLoaderRoute: typeof ExperienceSecopsBookRouteImport
      parentRoute: typeof ExperienceSecopsRoute
    }
    '/experience/secops/ai': {
      id: '/experience/secops/ai'
      path: '/ai'
      fullPath: '/experience/secops/ai'
      preLoaderRoute: typeof ExperienceSecopsAiRouteImport
      parentRoute: typeof ExperienceSecopsRoute
    }
    '/experience/secops/tour/$capability': {
      id: '/experience/secops/tour/$capability'
      path: '/$capability'
      fullPath: '/experience/secops/tour/$capability'
      preLoaderRoute: typeof ExperienceSecopsTourCapabilityRouteImport
      parentRoute: typeof ExperienceSecopsTourRoute
    }
  }
}

interface ExperienceSecopsTourRouteChildren {
  ExperienceSecopsTourCapabilityRoute: typeof ExperienceSecopsTourCapabilityRoute
}

const ExperienceSecopsTourRouteChildren: ExperienceSecopsTourRouteChildren = {
  ExperienceSecopsTourCapabilityRoute: ExperienceSecopsTourCapabilityRoute,
}

const ExperienceSecopsTourRouteWithChildren =
  ExperienceSecopsTourRoute._addFileChildren(ExperienceSecopsTourRouteChildren)

interface ExperienceSecopsRouteChildren {
  ExperienceSecopsAiRoute: typeof ExperienceSecopsAiRoute
  ExperienceSecopsBookRoute: typeof ExperienceSecopsBookRoute
  ExperienceSecopsStoriesRoute: typeof ExperienceSecopsStoriesRoute
  ExperienceSecopsSuccessRoute: typeof ExperienceSecopsSuccessRoute
  ExperienceSecopsTourRoute: typeof ExperienceSecopsTourRouteWithChildren
  ExperienceSecopsWhyRoute: typeof ExperienceSecopsWhyRoute
  ExperienceSecopsIndexRoute: typeof ExperienceSecopsIndexRoute
}

const ExperienceSecopsRouteChildren: ExperienceSecopsRouteChildren = {
  ExperienceSecopsAiRoute: ExperienceSecopsAiRoute,
  ExperienceSecopsBookRoute: ExperienceSecopsBookRoute,
  ExperienceSecopsStoriesRoute: ExperienceSecopsStoriesRoute,
  ExperienceSecopsSuccessRoute: ExperienceSecopsSuccessRoute,
  ExperienceSecopsTourRoute: ExperienceSecopsTourRouteWithChildren,
  ExperienceSecopsWhyRoute: ExperienceSecopsWhyRoute,
  ExperienceSecopsIndexRoute: ExperienceSecopsIndexRoute,
}

const ExperienceSecopsRouteWithChildren =
  ExperienceSecopsRoute._addFileChildren(ExperienceSecopsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ExperienceSecopsRoute: ExperienceSecopsRouteWithChildren,
  ExperienceIndexRoute: ExperienceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
